version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0-focal
    steps:
      - checkout
      - run:
          name: CI
          command: |
            dotnet run --project ./build/Build.csproj
            
workflows:
  version: 2
  build:
    jobs:
      - build
